"""Add fdc_id column to User

Revision ID: 04776fc985a3
Revises: c4a2650adb95
Create Date: 2024-05-03 21:35:03.623319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04776fc985a3'
down_revision = 'c4a2650adb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fdc_id', sa.Integer(), nullable=True))
    op.add_column('user_query', sa.Column('fdc_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_query', 'fdc_id')
    op.drop_column('user', 'fdc_id')
    # ### end Alembic commands ###
