"""Increase username and password_hash column size

Revision ID: c4a2650adb95
Revises: 29e65a2a8fa7
Create Date: 2024-05-03 11:28:02.217030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a2650adb95'
down_revision = '29e65a2a8fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               comment=None,
               existing_comment='Hashed password for user authentication',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               comment='Hashed password for user authentication',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user', 'username',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
