"""Description of the migration

Revision ID: cc313b6b6a6b
Revises: 04776fc985a3
Create Date: 2024-05-03 21:55:45.376010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc313b6b6a6b'
down_revision = '04776fc985a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_product', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('food_product', sa.Column('ingredients', sa.Text(), nullable=True))
    op.add_column('food_product', sa.Column('fdc_id', sa.Integer(), nullable=True))
    op.add_column('user_query', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_query', 'food_product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_query', type_='foreignkey')
    op.drop_column('user_query', 'product_id')
    op.drop_column('food_product', 'fdc_id')
    op.drop_column('food_product', 'ingredients')
    op.drop_column('food_product', 'brand')
    # ### end Alembic commands ###
