"""Add dataType column to FoodProduct model

Revision ID: f9ed4c6bd644
Revises: cc313b6b6a6b
Create Date: 2024-05-06 22:26:47.252357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ed4c6bd644'
down_revision = 'cc313b6b6a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_product', sa.Column('dataType', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_product', 'dataType')
    # ### end Alembic commands ###
